version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smartsalud_v2_db
    environment:
      POSTGRES_USER: smartsalud_user
      POSTGRES_PASSWORD: smartsalud_pass
      POSTGRES_DB: smartsalud_v2
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartsalud_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: smartsalud_v2_redis
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: smartsalud_v2_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://smartsalud_user:smartsalud_pass@postgres:5432/smartsalud_v2
      REDIS_URL: redis://redis:6379/0
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
      - ../token.json:/app/token.json  # Google Calendar credentials
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data:
